// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efeqesosyrsztqnmjhwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmZXFlc29zeXJzenRxbm1qaHd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1Mjc3MzgsImV4cCI6MjA2MjEwMzczOH0.4AttIbqdRIswczGpI6MpkyUaw9uIxxcKE3CyTU-9c0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);